// 변경 이유: 쿠팡 밀크런 계산에 필요한 품목 마스터 데이터를 분리해 재사용성을 높였습니다.
export interface CoupangProduct {
  id: string;
  company: "쿠팡" | "씨피엘비";
  name: string;
  unit: number;
  carton: number | null;
  palletCarton: number | null;
  palletQty: number | null;
  stacking: string;
}

export const COUPANG_PRODUCTS: CoupangProduct[] = [
  {
    id: "p01",
    company: "쿠팡",
    name: "붙이는하루온팩",
    unit: 10,
    carton: 24,
    palletCarton: 60,
    palletQty: 1440,
    stacking: "12 x 5단",
  },
  {
    id: "p02",
    company: "쿠팡",
    name: "붙이는하루온팩",
    unit: 20,
    carton: 12,
    palletCarton: 60,
    palletQty: 720,
    stacking: "12 x 5단",
  },
  {
    id: "p03",
    company: "쿠팡",
    name: "붙이는하루온팩",
    unit: 40,
    carton: 6,
    palletCarton: 60,
    palletQty: 360,
    stacking: "12 x 5단",
  },
  {
    id: "p04",
    company: "쿠팡",
    name: "붙이는하루온팩",
    unit: 50,
    carton: 5,
    palletCarton: 48,
    palletQty: 240,
    stacking: "12 x 4단",
  },
  {
    id: "p05",
    company: "쿠팡",
    name: "박상병 150g",
    unit: 10,
    carton: 16,
    palletCarton: 24,
    palletQty: 384,
    stacking: "6 x 4단",
  },
  {
    id: "p06",
    company: "쿠팡",
    name: "박상병 150g",
    unit: 30,
    carton: 5,
    palletCarton: 24,
    palletQty: 120,
    stacking: "6 x 4단(전용박스)",
  },
  {
    id: "p07",
    company: "쿠팡",
    name: "박상병 150g",
    unit: 40,
    carton: 4,
    palletCarton: 24,
    palletQty: 96,
    stacking: "6 x 4단(전용박스)",
  },
  {
    id: "p08",
    company: "쿠팡",
    name: "손난로80g",
    unit: 10,
    carton: 24,
    palletCarton: 48,
    palletQty: 1152,
    stacking: "12 x 4단",
  },
  {
    id: "p09",
    company: "쿠팡",
    name: "손난로80g",
    unit: 20,
    carton: 10,
    palletCarton: 48,
    palletQty: 480,
    stacking: "12 x 4단",
  },
  {
    id: "p10",
    company: "쿠팡",
    name: "손난로80g",
    unit: 30,
    carton: 7,
    palletCarton: 48,
    palletQty: 336,
    stacking: "12 x 4단",
  },
  {
    id: "p11",
    company: "쿠팡",
    name: "손난로80g",
    unit: 40,
    carton: 5,
    palletCarton: 48,
    palletQty: 240,
    stacking: "12 x 4단",
  },
  {
    id: "p12",
    company: "쿠팡",
    name: "대용량150g",
    unit: 10,
    carton: 10,
    palletCarton: 40,
    palletQty: 400,
    stacking: "8 x 5단",
  },
  {
    id: "p13",
    company: "쿠팡",
    name: "대용량150g",
    unit: 30,
    carton: 5,
    palletCarton: 24,
    palletQty: 120,
    stacking: "6 x 4단",
  },
  {
    id: "p14",
    company: "쿠팡",
    name: "대용량150g",
    unit: 40,
    carton: 4,
    palletCarton: 24,
    palletQty: 96,
    stacking: "6 x 4단",
  },
  {
    id: "p15",
    company: "쿠팡",
    name: "발열귀마개(본품)",
    unit: 10,
    carton: 18,
    palletCarton: 16,
    palletQty: 288,
    stacking: "4 x 4단",
  },
  {
    id: "p16",
    company: "쿠팡",
    name: "발난로(2×5매)",
    unit: 30,
    carton: 16,
    palletCarton: 60,
    palletQty: 960,
    stacking: "12 x 5단(골드)",
  },
  {
    id: "p17",
    company: "쿠팡",
    name: "발가락10매",
    unit: 10,
    carton: 40,
    palletCarton: 30,
    palletQty: 1200,
    stacking: "6 x 5단",
  },
  {
    id: "p18",
    company: "쿠팡",
    name: "깔창형발난로2매",
    unit: 10,
    carton: 20,
    palletCarton: 30,
    palletQty: 600,
    stacking: "6 x 5단(박상병)",
  },
  {
    id: "p19",
    company: "쿠팡",
    name: "(CN)하루온군인핫팩",
    unit: 10,
    carton: 12,
    palletCarton: 40,
    palletQty: 480,
    stacking: "8 x 5단",
  },
  {
    id: "p20",
    company: "쿠팡",
    name: "(CN)불가마박일병핫팩",
    unit: 10,
    carton: 12,
    palletCarton: null,
    palletQty: null,
    stacking: "",
  },
  {
    id: "p21",
    company: "쿠팡",
    name: "(CN)불가마붙이는핫팩",
    unit: 20,
    carton: 15,
    palletCarton: null,
    palletQty: null,
    stacking: "",
  },
  {
    id: "p22",
    company: "쿠팡",
    name: "박상병 100g",
    unit: 30,
    carton: 6,
    palletCarton: 24,
    palletQty: 144,
    stacking: "6 x 4단",
  },
  {
    id: "p23",
    company: "쿠팡",
    name: "박상병 80g",
    unit: 40,
    carton: 5,
    palletCarton: null,
    palletQty: null,
    stacking: "",
  },
  {
    id: "p24",
    company: "쿠팡",
    name: "하루온미니(붙이는)",
    unit: 30,
    carton: 16,
    palletCarton: 40,
    palletQty: 640,
    stacking: "8 x 5단",
  },
  {
    id: "p25",
    company: "쿠팡",
    name: "손난로미니",
    unit: 30,
    carton: 16,
    palletCarton: 32,
    palletQty: 512,
    stacking: "8 x 4단",
  },
  {
    id: "p26",
    company: "쿠팡",
    name: "아랫배케어5매",
    unit: 4,
    carton: 10,
    palletCarton: 32,
    palletQty: 320,
    stacking: "8 x 4단",
  },
  {
    id: "p27",
    company: "씨피엘비",
    name: "비타할로 아이조아",
    unit: 14,
    carton: 60,
    palletCarton: 12,
    palletQty: 720,
    stacking: "4 x 3단",
  },
  {
    id: "p28",
    company: "씨피엘비",
    name: "비타할로 아랫배",
    unit: 30,
    carton: 36,
    palletCarton: 12,
    palletQty: 432,
    stacking: "4 x 3단",
  },
  {
    id: "p29",
    company: "씨피엘비",
    name: "탐사파스형",
    unit: 50,
    carton: null,
    palletCarton: null,
    palletQty: 240,
    stacking: "24 x 10단",
  },
];
